spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 5MB
  redis:
    password: hxzy
    host: 192.168.25.163
    lettuce:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 200
        max-wait: 10000
    port: 6379
  application:
    name: shop
#    sentinel:
#      master:  mymaster
#      nodes:
#        - 192.168.1.180:26379
#        - 192.168.1.180:26380
#        - 192.168.1.180:26381
logging:
  file: shop.log
  level:
    com.hxzy: debug
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hxzy.entity
img:
  path: D:\\imgServer\\
  server: 'http://192.168.25.7:8080/imgcms/'
sms:
  forgetpwd:
    templateId: 549828
    expired_minute: 5
    retry_seconds: 120
    code_len: 5
    redis_prefix: 'student:findpwd:'
server:
  port: 8080